name: Pipeline de CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Revisar el código
        uses: actions/checkout@v3

      - name: Instalar Node.js y HTMLHint
        run: |
          # Instalamos Node.js (si no está instalado) y HTMLHint
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g htmlhint

      - name: Ejecutar validación de HTML con HTMLHint
        run: |
          # Ejecutamos HTMLHint para validar los archivos HTML
          htmlhint index.html

  pruebas:
    runs-on: ubuntu-latest
    needs: construir
    steps:
      - name: Revisar el código
        uses: actions/checkout@v3

      - name: Ejecutar pruebas de validación de HTML
        run: |
          htmlhint index.html

  desplegar:
    runs-on: ubuntu-latest
    needs: pruebas
    steps:
      - name: Revisar el código
        uses: actions/checkout@v3

      - name: Empaquetar la aplicación para el despliegue
        run: |
          # Empaquetamos los archivos en un archivo .zip
          zip -r website.zip .
          # Simulamos el despliegue subiendo el archivo comprimido como artefacto
          echo "Desplegando website.zip"
