name: Pipeline de CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Revisar el código
        uses: actions/checkout@v3

      - name: Verificar archivos HTML
        run: 
          sudo apt-get install -y html-xml-utils
          htmldoc -v index.html

  pruebas:
    runs-on: ubuntu-latest
    needs: construir
    steps:
      - name: Revisar el código
        uses: actions/checkout@v3

      - name: Instalar HTMLHint
        run: npm install htmlhint

      - name: Ejecutar validación de HTML
        run: 
          htmlhint index.html

  desplegar:
    runs-on: ubuntu-latest
    needs: pruebas
    steps:
      - name: Revisar el código
        uses: actions/checkout@v3

      - name: Empaquetar la aplicación para el despliegue
        run: 
          zip -r paginaWebCR7.zip .
          echo "Desplegando paginaWebCR7.zip"
